import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Transcript Kasetsart University",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <div className="text-center text-2xl p-5 font-bold">
            เว็บไซต์ตรวจสอบใบจบการศึกษาภาควิชาวิทยาการคอมพิวเตอร์ <br />ณ มหาวิทยาลัยเกษตรศาสตร์ บางเขน
          </div>
          {children}
        </Provider>
      </body>
    </html>
  );
}
